export const categories = [
    'Roupas Esportivas',
    'Calçados Esportivos',
    'Equipamentos de Treino',
    'Acessórios para Esportes',
    'Suplementos e Nutrição',
    'Equipamentos de Futebol',
    'Equipamentos de Basquete',
    'Equipamentos de Corrida',
    'Equipamentos de Natação',
    'Equipamentos de Tênis',
    'Equipamentos de Ciclismo',
    'Equipamentos de Yoga',
    'Equipamentos de CrossFit',
    'Equipamentos de Golfe',
    'Equipamentos de Artes Marciais',
    'Equipamentos de Esportes ao Ar Livre',
    'Mochilas e Sacolas Esportivas',
    'Roupas de Frio para Esportes',
    'Produtos para Recuperação Muscular',
    'Acessórios para Saúde e Bem-Estar',
  ];